CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FullName NVARCHAR(160) NOT NULL,
    Email NVARCHAR(180) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(512) NOT NULL,
    Role NVARCHAR(40) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE RefreshTokens (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    TokenHash NVARCHAR(256) NOT NULL UNIQUE,
    ExpiresAt DATETIMEOFFSET NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSUTCDATETIME(),
    RevokedAt DATETIMEOFFSET NULL,
    CONSTRAINT FK_RefreshTokens_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Categories (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE Products (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(180) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    CostPrice DECIMAL(18,2) NOT NULL,
    StockQuantity INT NOT NULL,
    ReorderLevel INT NOT NULL DEFAULT 10,
    IsActive BIT NOT NULL DEFAULT 1,
    CategoryId INT NOT NULL,
    CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
);

CREATE TABLE Sales (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Subtotal DECIMAL(18,2) NOT NULL,
    DiscountAmount DECIMAL(18,2) NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    ProfitAmount DECIMAL(18,2) NOT NULL,
    Date DATETIMEOFFSET NOT NULL,
    CashierId UNIQUEIDENTIFIER NOT NULL,
    PaymentMethod NVARCHAR(40) NOT NULL,
    ReceiptNumber NVARCHAR(40) NOT NULL UNIQUE,
    CONSTRAINT FK_Sales_Users FOREIGN KEY (CashierId) REFERENCES Users(Id)
);

CREATE TABLE SaleItems (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    SaleId UNIQUEIDENTIFIER NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    CostPrice DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_SaleItems_Sales FOREIGN KEY (SaleId) REFERENCES Sales(Id),
    CONSTRAINT FK_SaleItems_Products FOREIGN KEY (ProductId) REFERENCES Products(Id)
);

CREATE TABLE InventoryLogs (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ProductId INT NOT NULL,
    ChangeAmount INT NOT NULL,
    Reason NVARCHAR(240) NOT NULL,
    Date DATETIMEOFFSET NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_InventoryLogs_Products FOREIGN KEY (ProductId) REFERENCES Products(Id)
);

CREATE TABLE AIInsights (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Type NVARCHAR(60) NOT NULL,
    Message NVARCHAR(4000) NOT NULL,
    Date DATETIMEOFFSET NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE INDEX IX_Products_Name ON Products(Name);
CREATE INDEX IX_Products_Category_Active ON Products(CategoryId, IsActive);
CREATE INDEX IX_Sales_Date ON Sales(Date);
CREATE INDEX IX_Sales_CashierId ON Sales(CashierId);
CREATE INDEX IX_SaleItems_Sale_Product ON SaleItems(SaleId, ProductId);
CREATE INDEX IX_InventoryLogs_ProductId ON InventoryLogs(ProductId);
CREATE INDEX IX_InventoryLogs_Date ON InventoryLogs(Date);
CREATE INDEX IX_AIInsights_Date ON AIInsights(Date);
